apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laligurans-mr5

resources:
- ../../base
- namespace.yaml
- tls-secret.yaml

patchesStrategicMerge:
- patches/ingress.yaml
- patches/configmap.yaml
- patches/namespace.yaml
- patches/frontend-deployment.yaml
- patches/backend-deployment.yaml

images:
- name: openlabfree/globomantics-be:v7
  newName: ghcr.io/elitexp/globomantics-hotel-backend
  newTag: 432f75f64bfb2edf489c25d99b1428c30c651c77
- name: openlabfree/globomantics-fe:v4
  newName: ghcr.io/elitexp/globomantics-hotel-frontend
  newTag: 432f75f64bfb2edf489c25d99b1428c30c651c77
