apiVersion: v1
kind: Secret
metadata:
  name: guestbook-backend-secret 
data:
  mongodb-username: "YWRtaW4="
  mongodb-password: "cGFzc3dvcmQ="
  s3-access-key: "T1RDR0s5RVU3OVJaS01WVUFJTkc="
  s3-secret-key: "ZlV6RmNSdnhvOHl6VGh3SEZscSt0d05Na1J3WVRQcWlFQVZhdHJkZQ=="
